version: '3.9'

services:
  frontend:
    build:
      context: ./frontend # Path to the frontend folder
    ports:
      - '8080:8080' # Maps port 8080 on the host to port 8080 in the container
    stdin_open: true # Keep STDIN open for the frontend dev server
    tty: true # Allocate a pseudo-TTY

  backend:
    build:
      context: ./backend # Path to the backend folder
    ports:
      - '8000:8000' # Maps port 8000 on the host to port 8000 in the container
    environment:
      - PYTHONUNBUFFERED=1 # Ensures logs are immediately flushed
    depends_on:
      - frontend # Ensures backend starts after the frontend is built
